version: "3.9"
services:
  mysql_db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hakimlivs

  api_service:
    build: .
    container_name: hakimlivs
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - mysql_db